Table user {
  id int [pk]

  email string [unique]
  password string
}


Table sender {
  id int [pk]
  // created by
  user_id int [ref: > user.id]

  device_id string [unique]
}


Table user_sender {
  user_id int [ref: > user.id]
  sender_id int [ref: > sender.id]

  indexes {
    (user_id, sender_id) [pk]
  }
}


enum ussr_requestor {
  user
  sender
}

enum ussr_status {
  requested
  accepted
  rejected
}

Table user_sender_req {
  id int [pk]
  user_id int [ref: > user.id]
  sender_id int [ref: > sender.id]
  requestor ussr_requestor
  status ussr_status
}

Table user_api_key {
  api_key string [pk]
  user int [ref: > user.id]
  api_secret string
  // expires after epoch 0 is deactivated
  expiresAfter timestamp
}

Table batch {
  id int [pk]
  queued_at timestamp
}

Table message {
  to string
  content string
  batch_id int [ref: > batch.id]

  sent_at timestamp

  user_id int [ref: > user.id]
  sent_from int [ref: > sender.id]
}
